import math
print(math.fabs(-5))
print(math.factorial(5))
print(math.floor(5.5))
print(math.gcd(36, 12))
print(math.exp(5))
print(math.pow(5, 3))
print(math.sqrt(81))
print(math.cos(0.5))
print(math.sin(0.5))
print(math.tan(0.5))
print(math.degrees(0.5))
print(math.radians(60))
print(math.pi)
print(math.e)
